# Generated by Django 5.1.2 on 2025-03-11 11:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('ville', models.CharField(blank=True, max_length=100, null=True)),
                ('etablissement', models.CharField(blank=True, max_length=100, null=True)),
                ('niveau', models.CharField(blank=True, max_length=50, null=True)),
                ('specialite', models.CharField(blank=True, max_length=100, null=True)),
                ('entreprise', models.CharField(blank=True, max_length=100, null=True)),
                ('mode_de_participation', models.CharField(blank=True, choices=[('solo', 'Solo'), ('equipe', 'Équipe')], max_length=10, null=True)),
                ('name_team', models.CharField(blank=True, max_length=100, null=True)),
                ('lien_vers_github', models.URLField(blank=True, null=True)),
                ('lien_vers_linkedin', models.URLField(blank=True, null=True)),
                ('competences_techniques', models.TextField(blank=True, null=True)),
                ('experience_en_ia', models.TextField(blank=True, null=True)),
                ('motivation', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
